development:
  adapter: mysql2
  encoding: utf8
  database: pair_study_development
  username: root
  password: mantra1000
  host: 127.0.0.1
  port: 3306

test: &test
  adapter: mysql2
  encoding: utf8
  database: pair_study_test
  username: root
  password: mantra1000
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: pair_study_production
  username: root
  password: mantra1000 #123456
  host: 127.0.0.1
  port: 3306

cucumber:
  <<: *test